### ISSUE TITLE
[BUG] - No crop option after camera

### ISSUE THREAD

**Issue by rexyrex** [CanHub/Android-Image-Cropper#24] opened 2021-01-04 07:18 UTC
**Issue:**
When selecting the default "camera" option, app does not go to crop screen after taking photo.

- Open selection menu 
- Select camera 
- Opens camera 
- Take picture 
- "Select or retake?" menu 
- On selecting "select", camera closes and nothing happens

**Expected Behavior**
- Open Selection menu
- Select Camera
- Opens camera
- Take picture
- "Select or Retake?" menu
- On selecting "select" crop view opens

**Device**
Android 10.
Galaxy Note 10+
implementation 'com.canhub.cropper:android-image-cropper:1.1.1'

**Code used to open selector**
`        CropImage.activity().setGuidelines(CropImageView.Guidelines.ON).setAspectRatio(1,1).start(activity);`

**Extra Info**
1. _(This used to work with the original library)_
2. Selecting photo from "Files" correctly opens crop view

**Comment by bohemima** [comment] 2021-01-04 08:32
Error seems to be "Failed to load sampled bitmap: content://<package>.cropper.fileprovider/my_images/Pictures/pickImageResult8398353326702376456.jpeg"

Is there missing steps in the documentation for FileProvider or permissions perhaps?

**Comment by VEIKKO99** [comment] 2021-01-04 12:44
I'm experiencing exactly the same bug. Code seems to fail here:
**BitmapFactory.Options decodeImageForOption(ContentResolver resolver, Uri uri)**

==> This check fails in  **BitmapSampled decodeSampledBitmap(Context context, Uri uri, int reqWidth, int reqHeight)** method:
`if (options.outWidth == -1 && options.outHeight == -1)
                throw new RuntimeException("File is not a picture");`

**Comment by Canato** [comment] 2021-01-04 18:12
@rexyrex I have another bug, but similar. When I try to run `Quick Sample` the camera option is not available, even if the permission is granted. 
Will look in to this bug later, in the main time I tag as `help wanted` and `good first issue` if someone else jump to help us. 

@bohemima your problem seen unrelated, but another one, please check this PR #10 where we did the FileProvider work. Should be fine, but maybe we hit another issue, let me know please

@VEIKKO99 could you get the same issue running the code `Quick Sample` build?

**Comment by bohemima** [comment] 2021-01-05 06:21
> @rexyrex I have another bug, but similar. When I try to run `Quick Sample` the camera option is not available, even if the permission is granted.

Only did a quick look around but it seems it is missing queries decleration for IMAGE_CAPTURE in the manifest, 

```
    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
    </queries>
```

> 
> @bohemima your problem seen unrelated, but another one, please check this PR #10 where we did the FileProvider work. Should be fine, but maybe we hit another issue, let me know please

I'm pretty sure it's the same issue, the crop screen is shown briefly before closing and the above error is sent.

**Comment by Canato** [comment] 2021-01-05 11:59
Great! =D
@bohemima any chance you can help here? Try to reproduce on the sample apps and propose a fix(PR)?

**Comment by VEIKKO99** [comment] 2021-01-05 14:34
> @VEIKKO99 could you get the same issue running the code `Quick Sample` build?

I'm not sure what you mean by Quick Sample build, but the error also occurs on the sample app.

**Comment by Sophie713** [comment] 2021-01-08 13:37
We are having the same issue. After you take the picture instead of offering to crop it it returns back to my activity.

**Comment by rexyrex** [comment] 2021-01-14 01:33
Version 2.0.0 fixed the issue for me. Camera -> crop now works

**Closed** 2021-01-14 08:57 UTC
Labels: bug, pinned

**Comment by SaltyBoi31** [comment] 2022-01-02 08:28
I have the same issue, but on Android 11. What change did Version 2.0.0 bring to fix the issue? (android noobie here)

**Comment by SaltyBoi31** [comment] 2022-01-02 08:50
> Version 2.0.0 fixed the issue for me. Camera -> crop now works

I have the same issue, but on Android 11. What change did Version 2.0.0 bring to fix the issue? (android noobie here)

**Comment by Canato** [comment] 2022-01-18 12:46
Hey @SaltyBoi31 try to use the latest library version and open a new issue (following the template) so I can help better ^^
