### ISSUE TITLE
[BUG] - Getting uriContent as null in CropImageView.CropResult

### ISSUE THREAD

**Issue by cybertronjc** [CanHub/Android-Image-Cropper#180] opened 2021-08-13 14:44 UTC
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [3.2.2]
 
**Describe the bug**
I have created a custom activity which includes CropImageView in my XML. Using DataBinding.
I am passing uri to  cropImageView.setImageUriAsync(incomingUri) and getting uri in cropImageView.setOnSetImageUriCompleteListener(). 

For getting Cropped result I have used async method  cropImageView.getCroppedImageAsync(), which gives me result in Bitmap but uriContent is Null.

**Expected behavior**
I should get the uriContent so that I can pass the uri back to fragment where I want to show the Cropped Image.

**Media**
When I click on the Center Check button I am calling cropImageView.getCroppedImageAsync()
![android-image-cropper-issue](https://user-images.githubusercontent.com/13762861/129374510-dc7679d6-2673-49d0-8f60-7d20857454a4.jpeg)

**Smartphone (please complete the following information):**
 - Device: [Xiomi A3, Android 11]
 - OS: [Android 11]

**Additional context**

**Comment by Canato** [comment] 2021-08-13 14:51
Hey @cybertronjc thanks for the detailed issue, helps a lot to understand your case.

This is our [sample code using crop image view](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_view/app/SCropImageViewFragment.kt)

Maybe it can help. 

You said:
> cropImageView.getCroppedImageAsync(), which gives me result

But this method should no return any result. 

did you override `fun onCropImageComplete(view: CropImageView, result: CropResult)` ?

Hope this piece of code can help:
```kt
private fun handleCropResult(result: CropResult?) {
        if (result != null && result.error == null) {
            val imageBitmap =
                if (binding.cropImageView.cropShape == CropImageView.CropShape.OVAL)
                    result.bitmap?.let { CropImage.toOvalBitmap(it) }
                else result.bitmap
            context?.let { Log.v("File Path", result.getUriFilePath(it).toString()) }
            SCropResultActivity.start(this, imageBitmap, result.uriContent, result.sampleSize)
        } else {
            Log.e("AIC", "Failed to crop image", result?.error)
            Toast
                .makeText(activity, "Crop failed: ${result?.error?.message}", Toast.LENGTH_SHORT)
                .show()
        }
    }
    ```

**Comment by cybertronjc** [comment] 2021-08-13 16:28
Hey @Canato 
I really appreciate the quick response. 

this is the centered check image (refer screenshot). On click of this check image I am calling cropImageView.getCroppedImageAsync(). and receiving the result in onCropImageComplete.
 ```
okayImg.setOnClickListener {
            viewBinding.progressCircular.visibility = View.VISIBLE
            cropImageView.getCroppedImageAsync()

        }
```

I have implemented the override function onCropImageComplete like this.

```
cropImageView.setOnCropImageCompleteListener(object : CropImageView.OnCropImageCompleteListener {
            override fun onCropImageComplete(
                view: CropImageView,
                result: CropImageView.CropResult
            ) {
                viewBinding.progressCircular.visibility = View.GONE
                handleCropResult(result)
            }

        })
```

```
private fun handleCropResult(result: CropImageView.CropResult) {
        if (result.isSuccessful && result.error == null) {
//            val imageBitmap =
//                if (viewBinding.cropImageView.cropShape == CropImageView.CropShape.OVAL)
//                    result.bitmap?.let { CropImage.toOvalBitmap(it) }
//                else result.bitmap
            Log.v("File Path",result.getUriFilePath(this).toString() )
            Log.v("File result", "result : ${result.bitmap.toString()} , ${result.cropRect.toString()}, ${result.uriContent.toString()} , :bimap , ${result.error}" )

            logger.d(ImageCropFragment.logTag, "cropped result  : ${result.uriContent.toString() }")
            //SCropResultActivity.start(this, imageBitmap, result.uriContent, result.sampleSize)
            val resultIntent = Intent()
            resultIntent.putExtra("croppedImage", result.uriContent.toString())
            setResult(Activity.RESULT_OK, resultIntent)
            finish()

        } else {
            Log.e("AIC", "Failed to crop image", result?.error)
         logger.d(ImageCropFragment.logTag, "Failed to crop image", result?.error.toString())

         Toast.makeText(this@ImageCropActivity, "Crop failed: ${result?.error?.message}", Toast.LENGTH_SHORT)
        }
    }

```

Still I get the uriContent as null but I am receiving the Bitmap which I don't want to use. check the debug screenshot below
<img width="1369" alt="Screenshot 2021-08-13 at 9 55 10 PM" src="https://user-images.githubusercontent.com/13762861/129390251-7237a235-a60a-46fe-8f28-1d57673d7226.png">

**Comment by Canato** [comment] 2021-08-13 16:35
Interesting bug, we need to take a look. What are you receiving from the UriFilePath?

And can you reproduce on the sample code?
Maybe is the device?

**Comment by cybertronjc** [comment] 2021-08-13 16:49
Hey @Canato 
Thanks for the response.
I am receiving result?.getUriFilePath(this) as null as well.

Allow me some time to reproduce the sample code.
Let me also try this on another device. This maybe because of Android 11 introduced scoped storage (not sure).

**Comment by Canato** [comment] 2021-08-13 16:56
I fix the scope storage last November. But let's keep investigating, I'm going for the weekend, but back on Monday

**Comment by cybertronjc** [comment] 2021-08-13 19:22
Hey @Canato 
I have reproduced the bug on the sample code in crop_image_view.
I am attaching a screenshot of the debug which shows uriContent value null on breakpoint line number 181 in SCropImageViewFragment.kt
The result?.getUriFilePath(this) is also null. Let's investigate more on Monday. thanks
<img width="1430" alt="Screenshot 2021-08-14 at 12 41 46 AM" src="https://user-images.githubusercontent.com/13762861/129407955-3d08549a-ab42-4214-8182-f418c1dd5c29.png">

**Comment by Canato** [comment] 2021-08-16 17:13
Found it, is not exactly a bug, but something this library need improvement, since we come from Java, we have strange stuff and not so good documentation, like `CropImageView` has 3 methods `getCroppedImageAsync` the problem, is that any of it will give you a `uriContent` value as return. Just bitmap.

For getting `uri` you would need to use `saveCroppedImageAsync` method. This receive the `uri` so it know where to save the cropped image.

The library activity `CropImageActivity` create it own `outputUri`. This is the value that the library return later
(what make no sense... you need to pass the uri and will receive is same value later, but now we saved something on it)

For sure something that need refactor @@.

**Comment by Canato** [comment] 2021-08-16 18:13
Besides the fact we can use without any change, the code can be refactor and improve.

I'm working on this here: https://github.com/CanHub/Android-Image-Cropper/pull/185

Something still wrong, so is a draft by now.

**Comment by cybertronjc** [comment] 2021-08-18 13:26
Hey @Canato 
Sorry for the delay.
I am using the updated PR code and now when I am passing the uriContent , the image is blurred.
Any solution for that?

**Comment by Canato** [comment] 2021-08-18 15:28
> Any solution for that?

Hey @cybertronjc the PR is WIP state, not ready yet =D

**Comment by cybertronjc** [comment] 2021-08-18 17:01
Cool, No worries. As of now I have changed the default compression format to PNG. After that I am not getting the blurred image. thanks

**Comment by Avishek1989** [comment] 2021-08-19 12:17
Hey @Canato , when this will be fixed? I'm in the middle of the development process, suffering with same bug.

**Comment by cybertronjc** [comment] 2021-08-19 12:21
@Avishek1989  Hi I was also in the development process. I imported the library as a module and changes the files which @Canato has updated in the PR.

**Comment by Canato** [comment] 2021-08-19 13:24
Hey @Avishek1989 welcome =D

> Hey @Canato , when this will be fixed? I'm in the middle of the development process, suffering with same bug.

Important to make clear that I don't win anything with this library, I just handover the project because was without update for too long and is very useful. That said I do my best to fix the bugs and add features when I have time. But a lot of important contributions come from the community it self. Sadly I cannot answer you with a deadline so I don't commit to something I may not be able to keep. I mostly need to focus on my job that pays me hahahah (but we have the sponsor button in this library for this)

In other vision, please feel free to open the PR and suggest a solution for the case, I will take the time to review and we merge, like many others did already, what make our lib better and better.

Right know you can do a workaround like I suggest [here](https://github.com/CanHub/Android-Image-Cropper/issues/180#issuecomment-899676309) or can use the default library activity until this is improved. 
Or use the PR, like @cybertronjc is doing, I just do not recommend this, since I cannot guarantee is stable =/.

I maybe have time this weekend after pack some boxes (I'm on moving houses process)

**Closed** 2021-09-01 19:16 UTC
Labels: bug
