### ISSUE TITLE
[BUG] -  Android 11 CropImageView is not working.

### ISSUE THREAD

**Issue by lovemobile1234** [CanHub/Android-Image-Cropper#273] opened 2021-11-20 20:56 UTC
I set the CropImageView in my activity.(Java)
When I get the bitmap from Camera Intent, it's not working, but android 10 is working well.

**Comment by Canato** [comment] 2021-11-22 09:44
Hey welcome 👋 to the library and thanks for the Issue.

Can you please follow the `template` we have for issues? 🙏 
There are many points on the template and will help me to help you.

I will **close** 🔴  this issue so you can reopen following the template,

_Is important to remember that my work here is volunteer and to save time and have better answer help me that people use the templates._ 

Thanks!! 🎉

Obs: Possible duplicate of #253 hard to be sure without more information

**Closed by Canato** 2021-11-22 09:44 UTC
Labels: bug
