### ISSUE TITLE
[BUG] - setOnCropImageCompleteListener does not work

### ISSUE THREAD

**Issue by kingspride** [CanHub/Android-Image-Cropper#261] opened 2021-11-08 11:35 UTC
- Lib Version 3.3.6
 
**Describe the bug**
 setOnCropImageCompleteListener does not work
Lambda function never gets called.

**To Reproduce**
use the CropImageView, then:
create a Lambda function:
```kt
binding.cropImageView.setOnCropImageCompleteListener{ view, result ->
    Log.d("imageComplete", "does this even get called")
}
```
notice that it never gets called when moving and scaling the crop region.

**Expected behavior**
Lambda should get called when releasing the cropping rectangle so that the selected region can be automatically refreshed into i.E. a Preview Drawable

**Media**
<img src="https://user-images.githubusercontent.com/45198837/140734942-5bd4ddda-140b-46f1-b82d-619ee32b2eed.png" width=400>

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mix 2S and Pixel 4 Emulator
 - OS: Android 10 MIUI 12.5 and Android 10 with Play Services

**Comment by Canato** [comment] 2021-11-09 10:10
Hey @kingspride thanks for the detailed issue, helps a lot to understand and be useful ^^ 

> notice that it never gets called when moving and scaling the crop region.

It should only get called after you call to drop. While selecting the area, moving, scaling we are not cropping yet.
So the way method expectation is to be called after we call crop and after is complete, then we have a result in `setOnCropImageCompleteListener`. 

To use crop from the `cropImageView` you need to call `binding.cropImageView.croppedImageAsync()` 

Can check more in the [sample code](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_view/app/SCropImageViewFragment.kt).

Obs: We have a strange shadow bug that I was trying to fix last weekend, not lucky yet ;)

**Comment by Canato** [comment] 2021-11-09 10:10
I'm closing, since the behaviour looks ok from the text, let's reopen if need, let me know ^^

**Comment by kingspride** [comment] 2021-11-09 10:32
thanks for the clarification; but then I think the lib lacks an important feature.

I need to get the cropped image as soon as the user releases the cropping rectangle.

there's also a setOnSetCropOverlayReleasedListener which in principle does what I want, but unfortunately using this breaks the cropper's automatic zoom.
find a demo video here:
https://cloud.xtlk.de/index.php/s/wCPXQMMJKTSSQPS

maybe you want to look into that aswell.
also I dont know if you meant that by mentioning "Obs: We have a strange shadow bug that I was trying to fix last weekend, not lucky yet ;)"

otherwise, this is a really great lib. feels like a unix tool: does only one thing, but its very streamlined and good at that.

**Comment by Canato** [comment] 2021-11-09 10:41
This is what you mean by broke zoom?

<img width="224" alt="Screenshot 2021-11-09 at 10 40 22" src="https://user-images.githubusercontent.com/15942449/140909485-f64af395-d9a1-4fcc-9049-6739c24a2474.png">

This is what I mean here:
> Obs: We have a strange shadow bug that I was trying to fix last weekend, not lucky yet ;)

If this is the bug, is not exactly related to the listener, but something else we need to fix, so you can use the `setOnSetCropOverlayReleasedListener` and hopefully we fix this bug soon, feel free to open a PR if you wanna fix faster ^^

**Comment by kingspride** [comment] 2021-11-09 10:45
yes. 
notice how the image doesnt zoom anymore when I reduce the cropping rectangle, while the rectangle does indeed resize itself. also the preview below shows the correctly zoomed portion.

If I dont use the Listener, its behaving normally.

**Comment by Canato** [comment] 2021-11-09 10:48
Exactly, I can reproduce this some times on normal usage, so I'm sure is not related to this listener =| 

But is some pain to fix this, since is not consistent, but maybe is consistent with `setOnSetCropOverlayReleasedListener ` what will make easier to fix, I will try to check on Friday/Saturday @@

**Comment by kingspride** [comment] 2021-11-11 12:24
... I just wanted to add that the zoom gets applied when dragging the cropping rectangle to an edge - maybe this helps finding the root cause ;)

**Comment by kingspride** [comment] 2022-01-05 15:34
I just ran some debugging on this matter and I think the error lies somewhere here:
![grafik](https://user-images.githubusercontent.com/45198837/148244317-6e05c9ad-bc02-4d6f-88c1-c6677c8832fc.png)
this is the state after I resized the cropping rectangle, and released it.

as you can see, the newZoom Value remains the same, but shouldnt it be different from mZoom ?

maybe this should be reopened.

**Comment by Canato** [comment] 2022-01-18 12:49
> as you can see, the newZoom Value remains the same, but shouldnt it be different from mZoom ?

On the line `1248` we set `mZoom` equal `newZoom` so is expected to have the same value. 

Why you believe they should be different?

**Comment by kingspride** [comment] 2022-01-18 13:03
Yeah I think its a misunderstanding. sorry.
I'll come back when I did more debugging.

**Comment by kingspride** [comment] 2022-02-17 12:51
I think I found the cause of the shadow bug:
as long as you dont have `getCroppedImage()` or `.croppedImage` in the `setOnSetCropOverlayReleasedListener`, the bug stays away.
but if you call it, the image zoom animation gets canceled in `getCroppedImage` on line 553 in `CropImageView.kt`

also, if I would use `croppedImageAsync()` in combination with `setOnCropImageCompleteListener`, the shadow bug persists because `startCropWorkerTask()` clears the animation aswell. (line 961 in `CropImageView.kt`)

**Comment by Canato** [comment] 2022-02-17 13:53
Will take a better look ASAP, but if you found consistency, let's open a PR and merge it =D

**Comment by kingspride** [comment] 2022-02-18 12:23
ready to merge :)

**Comment by Canato** [comment] 2022-02-18 15:49
@kingspride I'm having a little of problem finding time to test the ticket, but will soon XD. Thanks for the amazing work

**Closed** 2022-02-20 16:22 UTC
Labels: bug, pinned
