### ISSUE TITLE
Android 13 (SDK 33): CropImageView white on some Samsung devices

### ISSUE THREAD

**Issue by manuel-tud** [CanHub/Android-Image-Cropper#599] opened 2023-11-07 12:37 UTC
Hi,
I've an app with 100k+ installs out there. Recently I've updated the target SDK version to 33 without changing anything on the image cropping code. Since that update I receive lots of complaints from users with various (not all) Samsung devices running Android 13 saying that the CIV doesn't load the chosen image and just stays white.
I load the image using the setImageUriAsync() method. Unfortunately I was not able to reproduce that bug on my test devices (which are not made by Samsung). I was also not able to reproduce it using Samsung's Test Lab devices.
But by the amount of bug report messages (including screenshots showing the behavior) I get, I can say for sure, that there is a bug.

(This could by the same bug mentioned here: https://github.com/CanHub/Android-Image-Cropper/issues/593)

**Comment by vanniktech** [comment] 2023-11-07 17:09
Can you reproduce and try to submit a PR which fixes this?

**Comment by anmol14dev** [comment] 2023-11-16 19:50
Facing same issue on my samsung device. I can see the image with crop square but white screen all around.

**Comment by Devenom1** [comment] 2023-12-15 10:21
Same issue here. But not just Samsung Phones. Motorola phones too. I don't have direct access to the devices facing the issue.

**Comment by HamzaAkram-shyk** [comment] 2023-12-19 10:06
Facing the same issue on my Vivo device. I can see the image with a crop square but a white screen all around. there is no option to go back and get the cropped image's Uri.

**Comment by kevschweitzer** [comment] 2023-12-29 02:53
Same issue here. I Could handle it by implementing a CustomActivity as stated in documentation and in sample app.


Custom activity code
`import android.net.Uri
import android.os.Bundle
import com.canhub.cropper.CropImageActivity
import dac.corp.dactive.databinding.ActivityCustomCropImageBinding

class CustomCropImageActivity : CropImageActivity() {

    private lateinit var binding: ActivityCustomCropImageBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        binding = ActivityCustomCropImageBinding.inflate(layoutInflater)
        super.onCreate(savedInstanceState)
        setContentView(binding.root)
        setListener()
        setCropImageView(binding.cropImageView)
    }

    private fun setListener() {
        binding.button.setOnClickListener { cropImage() }
    }

    override fun onPickImageResult(resultUri: Uri?) {
        super.onPickImageResult(resultUri)

        if (resultUri != null) {
            binding.cropImageView.setImageUriAsync(resultUri)
        }
    }
}`

Custom Activity Layout
`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".utilities.CustomCropImage.CustomCropImageActivity">

    <com.canhub.cropper.CropImageView
        android:id="@+id/cropImageView"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toTopOf="@id/button"/>

    <Button
        android:id="@+id/button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="ACEPTAR"
        app:layout_constraintTop_toBottomOf="@id/cropImageView"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"/>

</androidx.constraintlayout.widget.ConstraintLayout>`

And this is the code to start the activity. 

1. You register the activity for result with a new Contract I created to change de Activity that will start (to put my own). I put it below 
2. you launch the activity in some button with the options you want (in my case I only wanted gallery and a square aspect ratio.

`
private val cropImage = registerForActivityResult(CustomCropImageContract()) { result ->
        if (result.isSuccessful) {
            result.uriContent?.let {
                val bitmap = mapUriToBitmap(it)
                viewModel.setNewPhoto(bitmap)
            }
        }
    }


cropImage.launch(
                CropImageContractOptions(null, CropImageOptions(
                    imageSourceIncludeGallery = true,
                    imageSourceIncludeCamera= false,
                    fixAspectRatio = true
                ))
            )
`

The custom contract here

`
class CustomCropImageContract : ActivityResultContract<CropImageContractOptions, CropImageView.CropResult>() {
    override fun createIntent(context: Context, input: CropImageContractOptions) = Intent(context, CustomCropImageActivity::class.java).apply {
        putExtra(
            CropImage.CROP_IMAGE_EXTRA_BUNDLE,
            Bundle(2).apply {
                putParcelable(CropImage.CROP_IMAGE_EXTRA_SOURCE, input.uri)
                putParcelable(CropImage.CROP_IMAGE_EXTRA_OPTIONS, input.cropImageOptions)
            },
        )
    }

    override fun parseResult(
        resultCode: Int,
        intent: Intent?,
    ): CropImageView.CropResult {
        val result = intent?.parcelable<CropImage.ActivityResult>(CropImage.CROP_IMAGE_EXTRA_RESULT)

        return if (result == null || resultCode == Activity.RESULT_CANCELED) {
            CropImage.CancelledResult
        } else {
            result
        }
    }
}
`

**Comment by Alex-Dobrynin** [comment] 2024-01-07 10:14
@vanniktech 
Same here. Will this be fixed?

**Comment by SourabhSuman007** [comment] 2024-05-15 06:49
@vanniktech Is this issue fixed in the latest release?

**Comment by vanniktech** [comment] 2024-05-15 07:23
Has something changed since my last comment? https://github.com/CanHub/Android-Image-Cropper/issues/599#issuecomment-1799260477

**Comment by omiwrench** [comment] 2024-07-03 12:04
Same issue here, using a Pixel 6 emulator with API 34.

**Comment by vanniktech** [comment] 2024-08-05 08:53
Roll your own activity and just use the CropImageView. Or alternatively use the workaround: https://github.com/CanHub/Android-Image-Cropper/issues/599#issuecomment-1871691074

Long term, I want to get rid of all the contracts & CropImageActivity.

**Closed by vanniktech** 2024-08-05 08:53 UTC
