### ISSUE TITLE
[BUG] - I can't connect the library to the project

### ISSUE THREAD

**Issue by Scorpionstvo** [CanHub/Android-Image-Cropper#392] opened 2022-06-24 10:51 UTC
My gradle can't sync.
I receive message: Failed to resolve: com.github.CanHub:Android-Image-Cropper:3.2.1

buildscript {
    
    ext {
        kotlinVersion = '1.6.10'
        retrofit_version = "2.9.0"
        okhttp_version = "5.0.0-alpha.6"
        nav_version = "2.4.2"
        rxAndroidVersion = '3.0.0'
    }
    dependencies {
        repositories {
            mavenCentral()
            maven { url ' https://jitpack.io ' }
            maven { url "https://google.bintray.com/flexbox-layout" }
            google()
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.3'
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath "io.realm:realm-gradle-plugin:10.9.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

plugins {
    id 'com.android.application' version '7.1.3' apply false
    id 'com.android.library' version '7.1.3' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.21' apply false
    id 'io.realm.kotlin' version '0.11.1' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

***

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id "androidx.navigation.safeargs.kotlin"
    id 'kotlin-kapt'
    id 'kotlin-android'
    id 'io.realm.kotlin'
}

android {
    compileSdk 32

    defaultConfig {
        applicationId "com.talker.android"
        minSdk 23
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

}

dependencies {
 implementation 'com.github.CanHub:Android-Image-Cropper:3.2.1' }

Please, help me implement your beautiful library

**Comment by navneethh** [comment] 2022-06-25 07:57
i dont have any problem while gradle sycing but the cropImage class is not there as java class & cropVew is too not found in xml

**Comment by Canato** [comment] 2022-06-28 08:51
Hey @Scorpionstvo welcome, could you please format your question so all the code will be in a code block? make it easier to read ^^

Did you try the latest releaser version to see if compiles?

**Comment by Vaspit** [comment] 2022-07-02 21:35
Hi. I had the same problem and not only for this cropper.

It looks like the problem is in build.grudle file and settings.gradle files. I placed `maven { url 'https://jitpack.io' }` to 3 places

1 place within build.grudle file:
```
...
buildscript {

    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
...
```

And 2 places within settings.gradle file:
```
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```

And now I can build the project

**Comment by Scorpionstvo** [comment] 2022-07-21 09:13
> И теперь я могу построить проект

< Thank you very much! It worked! I added once line in my settings.gradle:
`pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
         maven { url 'https://jitpack.io' }
    }
}`

**Comment by vivekgupta4Git** [comment] 2022-07-24 19:14
Worked for me too.

**Closed** 2022-07-26 18:37 UTC
Labels: bug
