### ISSUE TITLE
[BUG] - Can we open only Gallery option ?

### ISSUE THREAD

**Issue by HafijurRahmanEjaro** [CanHub/Android-Image-Cropper#413] opened 2022-07-25 14:34 UTC
**Can we open only Gallery option ?**
I want to show only Gallery option and no need camera and other option is that possible? 

please help me out regarding the same.

**Comment by vivekgupta4Git** [comment] 2022-07-26 06:41
well dude, I Guess,  you can override showImageSourceDialog() method , it is marked as open too. 

> This method show the dialog for user source choice, it is an open function so can be override and customised with the app layout if need.

**Comment by vivekgupta4Git** [comment] 2022-07-26 07:46
Override showImageSourceDialog() 
      This method shows the dialog for user source choice, it is an open function so can be  override and customised with the app layout if need.

**Comment by Canato** [comment] 2022-07-26 18:41
Hey @HafijurRahmanEjaro welcome 👋 

That's not a bug, please next time open on [discussions](https://github.com/CanHub/Android-Image-Cropper/discussions)

You can check the [feature list](https://github.com/CanHub/Android-Image-Cropper/blob/main/.documentation/features.md) we have

You are looking for 
```kt
setImageSource(
  includeGallery = true,
  includeCamera = false,
)
```

**Closed by Canato** 2022-07-26 18:41 UTC
Labels: bug
